spring.application.name=FilmRentalFrontend
server.port=8081
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
backend.api.url=http://localhost:8080/api/films

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
#backend.api.url=http://localhost:8080/api/actors
logging.level.com.filmrentalfrontend=DEBUG